
project_name: mthfd1
project_description: Sdelci et al (2018) - MTHFD1 is a genetic interactor of BRD4 and links folate metabolism to transcriptional regulation
username: arendeiro
email: arendeiro@cemm.oeaw.ac.at

metadata:
  output_dir: /scratch/lab_bock/shared/projects/mthfd1
  results_subdir: data
  submission_subdir: runs
  pipeline_interfaces: /home/arendeiro/workspace/open_pipelines/pipeline_interface.yaml
  sample_annotation: /scratch/lab_bock/shared/projects/mthfd1/metadata/annotation.csv
  sample_subannotation: /scratch/lab_bock/shared/projects/mthfd1/metadata/merge_table.csv
  comparison_table: /scratch/lab_bock/shared/projects/mthfd1/metadata/comparison_table.csv

sample_attributes:
 - sample_name
 - cell_line
 - library
 - condition
 - knockout_clone
 - ip
 - antibody_clone
 - replicate
 - experiment_name
 - experiment_abbrv

group_attributes:
 - cell_line
 - condition
 - knockout_clone
 - ip
 - antibody_clone
 - replicate
 - experiment_abbrv

data_sources:
  # specify the ABSOLUTE PATH of input files using variable path expressions
  # entries correspond to values in the data_source column in sample_annotation table
  # {variable} can be used to replace environment variables or other sample_annotation columns
  # If you use {variable} codes, you should quote the field so python can parse it.
  bsf: /scratch/lab_bsf/samples/{flowcell}/{flowcell}_{lane}_samples/{flowcell}_{lane}#{BSF_name}.bam

genomes:
  human: hg19

compute:
  submission_template: slurm_template.sub
  submission_command: sbatch

trackhubs:
  trackhub_dir: /data/groups/lab_bock/public_html/arendeiro/mthfd1/
  url: http://biomedical-sequencing.at/bocklab/arendeiro/mthfd1
  # http://genome-euro.ucsc.edu/cgi-bin/hgTracks?db=hg19&hubUrl=http%3A%2F%2Fbiomedical-sequencing.at%2Fbocklab%2Farendeiro%2Fmthfd1%2Fhub.txt
